apiVersion: v1
kind: PersistentVolume
metadata:
    name: vprodb-pv # Name of the Persistent Volume
spec:
    capacity:
        storage: 3Gi # Size of the storage (3 GiB)
    accessModes:
        - ReadWriteOnce # This volume can be mounted as read-write by a single node
    persistentVolumeReclaimPolicy: Retain # What happens to the volume when released

    awsElasticBlockStore: # Specifies AWS Elastic Block Store as the storage type
        volumeID: vol-06698acb30990d0a2 # The ID of the AWS volume
        fsType: ext4 # File system type used on the volume
