apiVersion: v1
kind: PersistentVolume
metadata:
    name: vprodb-pv
spec:
    capacity:
        storage: 3Gi
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    awsElasticBlockStore:
        volumeID: vol-0f72cb8ec19846f86
        fsType: ext4
    nodeAffinity:
        required:
            nodeSelectorTerms:
                - matchExpressions:
                      - key: topology.kubernetes.io/zone
                        operator: In
                        values:
                            - us-east-1a
    storageClassName: 'kops-csi-1-21'
