apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: vprodb-pvc # Name of the PVC
spec:
    accessModes:
        - ReadWriteOnce # This claim can be used by a single node in read-write mode
    resources:
        requests:
            storage: 3Gi # The amount of storage requested

