apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: vprodb-pvc
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 3Gi
    storageClassName: my-storage-class # Refer to the storage class
