apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: my-storage-class
provisioner: kubernetes.io/aws-ebs
parameters:
    type: gp2 # Change to your preferred volume type
    zones: us-east-2a # Ensure this is correct for your setup
    iopsPerGB: '10'
    fsType: ext4
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
